# Generated by Django 5.0.6 on 2026-05-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downtimes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="log",
            name="problem",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="error_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="downtimes.errorcode",
            ),
        ),
    ]
